baseURL = "https://blog.codingmilitia.com"
languageCode = "en-us"
title = "Coding Militia"
description = "Code, headbang, grouch, repeat!"
# theme = "ananke"
DisqusShortname = "codingmilitia"
#googleAnalytics = "UA-58690226-4"
pygmentsCodeFences = true
enableRobotsTXT = true

[params]
  latest_posts_count = 5
  favicon = "assets/favicon.png"
  show_reading_time = true
  images = ["assets/logo.jpg"]
  description = "Code, headbang, grouch, repeat!"

[author]
  name = "Jo√£o Antunes"
  

[permalinks]
  posts = "/:year/:month/:day/:slug"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[markup]
  [markup.highlight]
    lineNos = true

# allow raw html in markdown files
[markup.goldmark.renderer]
  unsafe= true

[social]
  twitter = "joaofbantunes"